name: JSON updater

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'data'
      - name: Download JSON
        run: |
          mkdir -p data
          curl -L ${{ vars.JSON_ENDPOINT }}?data=type1 > data/data1.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=type2 > data/data2.json
      - name: Diff files
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'Update data'
          git push
        if: steps.diff.outcome == 'failure'
